###
### Comandos Internos:
### shutdown: Ao invés do console executar um comando ele irá reiniciar o servidor 
###
### Dias:
### 0 = Todos os dias, 1 = Domingo, 2 = Segunda, 3 = Terça,
### 4 = Quarta, 5 = Quinta, 6 = Sexta, 7 = Sábado
Threads:
 restart:
  horarios:
  - '0:05:00'
  - '0:14:00'
  - '0:23:00'
  executeCommand: 'shutdown'
 gladiador:
  horarios:
  - '7:20:00'
  executeCommand: 'gladiador iniciar'