registeredAddresses:
- '127.0.0.1'
- '158.69.153.222'
- '143.255.131.136'
games:
 auth:
  servers:
    auth: # id/key do servidor
      address: 158.69.153.222
      port: 25566
      maxPlayers: 100
  welcomeServers: [] #lista vazia significa que qualquer servidor pode receber
 lobby:
  servers:
    lobby: # id/key do servidor
      address: 158.69.153.222
      port: 25567
      maxPlayers: 100
  welcomeServers: [] #lista vazia significa que qualquer servidor pode receber
 fullpvp:
  servers:
    fullpvp: # id/key do servidor principal onde há mineração, loja, area vip e etc..
      address: 199.127.63.103
      port: 25566
      maxPlayers: 100
    fullpvp2: # id/key do servidor de eventos
      address: 199.127.63.103
      port: 25566
      maxPlayers: 150
  welcomeServers:
  - fullpvp